### ISSUE TITLE
ModuleNotFoundError: No module named 'rlutilities.rlutilities'

### ISSUE THREAD

**Issue by TheRocketBooster** [Darxeal/mirror-bot#1]
I'm probably doing something wrong, or my environment is setup incorrectly, but just in case, I wanted to see if anyone had also run into this issue. Here is the full traceback error when I try to run the mirror-bot: 

`Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\samve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\rlbot\setup_manager.py", line 776, in run_agent
    agent_class_wrapper = import_agent(python_file)
  File "C:\Users\samve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\rlbot\utils\class_importer.py", line 88, in import_agent
    return import_class_with_base(python_file, BaseAgent)
  File "C:\Users\samve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\rlbot\utils\class_importer.py", line 100, in import_class_with_base
    return ExternalClassWrapper(python_file, base_class)
  File "C:\Users\samve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\rlbot\utils\class_importer.py", line 33, in __init__
    self._load_external_class_and_record_module_changes()
  File "C:\Users\samve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\rlbot\utils\class_importer.py", line 37, in _load_external_class_and_record_module_changes
    self.loaded_class, self.loaded_module = load_external_class(self.python_file, self.base_class)
  File "C:\Users\samve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\rlbot\utils\class_importer.py", line 107, in load_external_class
    loaded_module = load_external_module(python_file)
  File "C:\Users\samve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\rlbot\utils\class_importer.py", line 133, in load_external_module
    loaded_module = importlib.import_module(module_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\samve\github\RLBotGUI\RLBotPackDeletable\RLBotPack-master\RLBotPack\MirrorBot\src\agent.py", line 10, in <module>
    from rlutilities.linear_algebra import vec3, mat3, rotation_to_euler, dot, look_at
  File "C:\Users\samve\github\RLBotGUI\RLBotPackDeletable\RLBotPack-master\RLBotPack\MirrorBot\src\rlutilities\__init__.py", line 4, in <module>
    from .rlutilities import mechanics, simulation, linear_algebra, initialize
ModuleNotFoundError: No module named 'rlutilities.rlutilities'`

**Comment by Darxeal** [comment]
botpack version only supports python 3.7 and 3.11 right now, you have python 3.9
you can download mirror bot from this repo, that should support 3.9 as well
